userprofile/urls.py
from django.urls import path

from .views import home, detail, register, signup, UserDetailView

app_name = "userprofile"
urlpatterns = [
    path('', home, name="home"),
    path('<int:pk>/detail/', UserDetailView.as_view(), name='detail'),
    path('signup/', signup, name="signup"),
    path('register/', register, name="register"),

]

userproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('userprofile.urls')), 
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include("django.contrib.auth.urls"))
]

handler404 = "userprofile.views.error_404"

userprofile/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone

from .managers import CustomUserManager


class CustomUser(AbstractBaseUser, PermissionsMixin):
    first_name = models.CharField(max_length= 100, default="", null=False, blank=False)
    last_name = models.CharField(max_length= 100, default="", null=False, blank=False)
    email = models.EmailField(_('email address'), unique=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateField(default=timezone.now)
    date_of_birth = models.DateField(default=timezone.now)
    address = models.CharField(max_length=400, blank=False, null=False, default="")
    
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['address', 'first_name', 'last_name']

    objects = CustomUserManager()
    
    def __str__(self):
        return self.email

userprofile/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

class SignUp(UserChangeForm):
    class Meta:
        password = forms.CharField(widget=forms.PasswordInput)
        model = CustomUser
        fields = ["first_name", "last_name", "email", "password", "is_active", "is_staff", "date_of_birth", "address"]

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = CustomUser
        fields = ["first_name", "last_name", "email", "date_of_birth", "address"]


"""class CustomUserCreationForm(forms.Form):
    first_name = forms.CharField(label='First Name', widget=forms.TextInput(attrs={"placeholder": "First Name"}))
    last_name = forms.CharField(label="Last Name", widget=forms.TextInput(attrs={"placeholder":"Last Name"}))
    email = forms.EmailField(label="Email")
    password1 = forms.CharField(label="Enter Password", widget=forms.PasswordInput(attrs={"placeholder":"Enter Password"}))
    password2 = forms.CharField(label="Confirm Password", widget=forms.PasswordInput(attrs={"placeholder":"Confirm Password"}))
    date_of_birth = forms.DateField(label="Date of Birth", widget=forms.DateInput(attrs={"type":"date", "placeholder":"Date of Birth"}))
    address = forms.CharField(widget=forms.Textarea(attrs={"rows": 5}))
    is_staff = forms.BooleanField()
    
    def clean_first_name(self):
        first_name = self.cleaned_data['first_name'].lower()
        if len(first_name) == 0:
            raise ValidationError("First Name can't be empty.")
        first_name = first_name.capitalize()
        return first_name
    
    def clean_last_name(self):
        last_name = self.cleaned_data['last_name'].lower()
        if len(last_name) == 0:
            raise ValidationError("Last Name can't be empty.")
        last_name = last_name.capitalize()
        return last_name
    
    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        user_email = CustomUser.objects.filter(email=email)
        if user_email.count():
            raise ValidationError("A user name with this email already exists.")
        return email

    def clean_password2(self):
        password1 = self.cleaned_data['password1'].lower()
        password2 = self.cleaned_data['password2'].lower()
         
        if (password1 and password2) and password1 != password2:
            raise ValidationError("Password don't match.")

        return password2
    
    def save(self, commit=True):
        first_name = self.cleaned_data['first_name']
        last_name = self.cleaned_data['last_name']
        email = self.cleaned_data['email']
        password2 = self.cleaned_data['password2']
        date_of_birth = self.cleaned_data['date_of_birth']
        address = self.cleaned_data['address']
        is_staff = self.cleaned_data['is_staff']
        user = CustomUser.objects.create(first_name=first_name, last_name=last_name, email=email, password=password2, date_of_birth=date_of_birth, address=address, is_staff=is_staff)
        return user

"""
class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ("email", 'first_name', 'last_name', 'address')

userprofile/views.py
from django.shortcuts import render, redirect

from django.contrib import messages
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin

from django.core.mail import send_mail

from django.views.defaults import page_not_found
from django.views.generic.detail import DetailView

from .forms import CustomUserCreationForm, SignUp
from .models import CustomUser

def home(request):
    users = CustomUser.objects.all()

    return render(request, "userprofile/home.html", {"users":users})

class UserDetailView(LoginRequiredMixin, DetailView):
    model = CustomUser
    template_name = "userprofile/detail.html"  
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

def detail(request, user_id):
    user = CustomUser.objects.get(pk=user_id)
    user = [(key, value) for key, value in user.__dict__.items()]
    print(user)
    return render(request, "userprofile/detail.html", {"user":user})

def register(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            send_mail('User Sign up', 'Thank you for signing up ' + str(form.cleaned_data['email']), 'junaidali0300@gmail.com', [str(form.cleaned_data['email'])], fail_silently=False)
            messages.success(request, "Account created successfully.")
            return redirect('userprofile:register')
    else:
        form = CustomUserCreationForm()

    return render(request, 'userprofile/register.html', {"form":form})

def signup(request):
    if request.method == "POST":
        form = SignUp(request.POST)
        if form.is_valid():
            form.save()
            send_mail('User Sign up', 'Thank you for signing up ' + str(form.cleaned_data['email']), 'junaidali0300@gmail.com', [str(form.cleaned_data['email'])], fail_silently=False)
            return redirect('userprofile:register')
    else:
        form = SignUp()

    return render(request, "userprofile/register.html", {"form":form})

def error_404(request, exception):
    if request.path.endswith("/detail/"):
        template_name = 'error/404.html'
    return page_not_found(request, exception, template_name=template_name)

userprofile/templates/userprofile/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    {% load static %}   
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'bootstrap.min.js' %}"></script>

    {% block css %}{% endblock %}
    {% block title %}<title>Document</title>{% endblock %}
</head>
<body>
    <div class="header">
        <img src="/static/img/ssps.jpg" alt="School"/>
        <div class="header-right">
            {% if user.is_authenticated %}
                <a href="{% url 'logout' %}">{{user.first_name}} ----- Logout</a>
            {% else %}
                <a href="{% url 'login' %}">Login</a>
                <a href="{% url 'userprofile:register' %}">Register</a>            
            {% endif %}
            <a href="/admin">Admin</a>
        </div>
    </div>

    {% block content %}
    {% endblock %}
</body>
</html>

userprofile/templates/userprofile/detail.html
{% extends "userprofile/base.html" %}

{% block content %}
    <h2>{{object.first_name}} {{object.last_name}}</h2>
    <h3>{{object.email}}</h3>
    <p>{{object.address}}</p>
{% endblock %}

userprofile/templates/userprofile/home.html
{% extends "userprofile/base.html" %}

{% block css %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/home.css' %}">
{% endblock %}

{% block content %}
    <div>
        {% for user in users %}
            <a class="list-margin" href="{% url 'userprofile:detail' user.id %}">{{ user.email }}, {{ user.first_name }}, {{ user.last_name }}</a>
            <br>
        {% endfor %}
    </div>
{% endblock %}

userprofile/templates/userprofile/register.html
{% extends "userprofile/base.html" %}

{% block css %}
    {% load crispy_forms_tags %}
    {% load static %}    
    <link rel="stylesheet" href="{% static 'css/signup.css' %}" type="text/css">
{% endblock %}

{% block content %}
    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
        
    <h2>Create account -- For Sir Syed Pilot School System</h2>
    <form method="POST">{% csrf_token %}
        <div class="form-group form-margin">
            {{ form|crispy }} 
            <input type="submit" name="submit" value="Register" class="btn btn-primary btn-block"/>
        </div>
    </form>

{% endblock %}